controller:
  replicaCount: 2
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  metrics:
    enabled: "true"
  nodeSelector: 
   beta.kubernetes.io/os: linux
  defaultBackend:
    nodeSelector:
      beta.kubernetes.io/os: linux
        

